### ISSUE TITLE
self signed certificate

### ISSUE THREAD

**Issue by kovalivan96** [kompot/nhl-tv-geeky-streams#24]
Hi!
After I choose a stream to download I get the message:

self signed certificate
Done in xx.xxs

And that's all
What can be the problem?

**Comment by kompot** [comment]
Well, right now no idea what may be the problem.

Could you paste everything that's output on the screen.

**Comment by kompot** [comment]
Ok, not much ;)

Please post everything about your environment that could help.
Windows version, docker version.

**Comment by kompot** [comment]
Actually, i might have found something related.
https://github.com/axios/axios/issues/535
Please try adding
`NODE_TLS_REJECT_UNAUTHORIZED=0`
line to `.env` file

**Comment by kompot** [comment]
Also you can try to change this line
https://github.com/kompot/nhl-tv-geeky-streams/blob/master/src/index.ts#L118
to 
`      cdnName: CDN.LEVEL3`

**Comment by kovalivan96** [comment]
Well...
If I NODE_TLS_REJECT_UNAUTHORIZED=0
line to .env file
I get the message "Request failed with status code 404"

Editing line #118 in index.ts changes nothing

**Comment by kompot** [comment]
Are you using latest version of this repository with docker image based on `node:alpine`?
https://github.com/kompot/nhl-tv-geeky-streams/blob/master/Dockerfile

**Comment by kovalivan96** [comment]
Yes

**Comment by kompot** [comment]
Can you try previous version, before switching to alpine based docker image
https://github.com/kompot/nhl-tv-geeky-streams/archive/c73a09013af056c57487ff5548241de94c4b43c2.zip

**Comment by kovalivan96** [comment]
Nothing changed :(

**Comment by Redmax87** [comment]
Go to C:\Windows\System32\drivers\etc
Open hosts file with notepad and delete any line with ...nhl.com.
Save hosts file.

**Comment by kompot** [comment]
@kovalivan96 any luck?

**Comment by rseanhall** [comment]
I think it's fair to assume that this a user-specific issue. No one else has reported it and the hosts file sounds like a likely root cause.
