### ISSUE TITLE
Add option to invoke multi-threaded download

### ISSUE THREAD

**Issue by caseyfw** [kompot/nhl-tv-geeky-streams#26]
Streamlink supports spawning multiple threads to simultaneously download a stream. This can REALLY speed up download times of archived games.

See https://streamlink.github.io/cli.html#cmdoption-hls-segment-threads

**Comment by kompot** [comment]
Will take a look at that, not sure I'll be able to test that - got a pretty slow connection over here.

Will write back here for you to test it.

**Comment by kompot** [comment]
I've added ability to customize `streamlink` with any options.
https://github.com/kompot/nhl-tv-geeky-streams/commit/b71410d111e13a10a992cc0414a18e7d8ca8d29e

Check out latest master.

**Comment by kompot** [comment]
Considering this working.

Feel free to reopen if it's not working for you.
