### ISSUE TITLE
Stream download speed is slow?

### ISSUE THREAD

**Issue by chiroptical** [kompot/nhl-tv-geeky-streams#30]
Using this tool earlier with a game from yesterday was perfectly fine, but I am getting really slow download speeds for streaming games. Is this expected?

For example, I just speed tested 100 Mb/s connection but streamlink writes at about 60 KB/s. I tried `--hls-segment-threads n` where `n = {1..4}`, but the speed didn't change at all. Any help is greatly appreciated.

**Comment by barrymoo** [comment]
It's possible I don't fully understand how these streams work, but if I choose a `--hls-start-offset` close to the current stream length I get decent download speeds. I guess this 60 KB/s is the actual new data from the stream.

Going to play around some more to figure this all out, but cool tool!

**Comment by barrymoo** [comment]
Honestly I have no idea. Even if I added `--player=mpv` it would never open.

> I was always just starting downloading and then run mpv manually.

This is what I did too. Just to make sure I understand, this is how your tool was intended to be used. It launches `streamlink` and you manually open the stream?

**Comment by kompot** [comment]
>Even if I added --player=mpv it would never open.
you have `mpv` in your path, right? * didn't test it, just curious *

anyway, if you find a way to launch media player right away - feel free to add it in config comments and make a PR; might be a good option for someone

> It launches streamlink and you manually open the stream?

Yep, exactly.

**Comment by barrymoo** [comment]
That is helpful. I will see if I can figure it out.
