### ISSUE TITLE
Negative match start times

### ISSUE THREAD

**Issue by kompot** [kompot/nhl-tv-geeky-streams#31]
![image](https://user-images.githubusercontent.com/231635/46510038-2398fb00-c84f-11e8-948a-b3d9bfb06681.png)

Seems like API has changed in some way and for live matches there are negative start times.
But not every time. After running again in a minute - everything is normal, match is selectable and downloadable.

![image](https://user-images.githubusercontent.com/231635/46510068-593de400-c84f-11e8-9051-5af5146f3ca6.png)

**Comment by rseanhall** [comment]
This was fixed in https://github.com/kompot/nhl-tv-geeky-streams/pull/39.
