### ISSUE TITLE
Request failed with status code 500

### ISSUE THREAD

**Issue by gacked** [kompot/nhl-tv-geeky-streams#33]
Hello, newbie here but love the concept.  The one complaint I have with nhl.tv games is that I cant take with me on long flights.  Was able to install app but keep getting this "error code 500" message when i select games. 
Any ideas how i might fix this (aside from learning more about coding - that's on my list)
I used the homebrew install for Mac OS and have tried on Mojave and Sierra OS

[Terminal Saved Output.txt](https://github.com/kompot/nhl-tv-geeky-streams/files/2613466/Terminal.Saved.Output.txt)

Thanks

**Comment by gacked** [comment]
Never mind.  I am an idiot.  Figured it out.  
Nice app, thanks.

**Comment by kompot** [comment]
Great!
Wrong credentials?

Feel free to make PR with documentation improvements if it might help others.

Will close this issue.

**Comment by gacked** [comment]
It was the right credentials but missed a space after the : on a side note, i dont seem to be able to navigate back/forward days on Mojave OS.  I can connect and download but can't change days.  However Sierra OS runs just fine.  Should I open a new issue or is there another simple fix that I'm missing?  Thanks!

**Comment by gacked** [comment]
Ok, i'll bang on it a bit and see what I can figure out, but will file an issue report.  Thanks!
(any help for my Blackhawks would be appreciated as well - that might be a larger issue though!)

**Comment by gacked** [comment]
just did a fresh re-install and it working now.  something must have corrupted on the prior install.  Didnt open a new issue.  Thanks
