### ISSUE TITLE
Download progress is lost with streamlink 1.0.0 (worked with 0.14.2)

### ISSUE THREAD

**Issue by kompot** [kompot/nhl-tv-geeky-streams#37]
Waiting for https://github.com/streamlink/streamlink/issues/2353 to be merged.
Was likely broken in https://github.com/streamlink/streamlink/issues/1770.

**Comment by rseanhall** [comment]
They rejected that feature request. Would you be open to going back to building streamlink from source, but from a custom fork with that feature request implemented?

**Comment by kompot** [comment]
No problem, PRs are welcome.

**Comment by kompot** [comment]
Thanks! Merging.
