### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by ghachey** [kompot/nhl-tv-geeky-streams#42]
Hi. I was really excite about this tool. I tried and I am getting.
```
$ ./node_modules/.bin/ts-node src/index.ts
? Choose game to download ⤺  one day back
? Choose game to download   Pittsburgh Penguins     @ Philadelphia Flyers    
? Choose feed to watch AWAY, ATT-PT
Unable to login to nhl.com. Username or password incorrect.
✨  Done in 35.12s.
```
I have changed my password three times to make sure it was not some sort of YAML related character parsing thing. Does this work with a nhl.tv account, because I have one and I can stream on Android app and website.

Thanks.

**Comment by ghachey** [comment]
I got the auth issue sorted. I had different emails with nhl.com and nhl.tv. Making them the same sorted the login.

**Comment by rubenflamshepherd** [comment]
To add more detail to this, nhl.com and nhl.tv are different accounts. I needed to align the username and passwords on both to deal with this error.

**Comment by kompot** [comment]
@rubenflamshepherd
Well, I guess it should not matter what are credentials for nhl.com
Only nhl.tv matters.

Clarified that in readme.
