### ISSUE TITLE
Error message after choosing stream quality

### ISSUE THREAD

**Issue by MatthiasReccius** [kompot/nhl-tv-geeky-streams#53]
After choosing the stream quality, instead of the download starting, I get the following error message in PowerShell:

```
ls: no such file or directory: ./video/*.mp4
Error: spawn streamlink ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:478:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

System: Windows 11

**Comment by rseanhall** [comment]
I always use Docker since it's a known good configuration. If you want to run directly on Windows, it will take more work. For example, it appears to require that streamlink.exe is in the path.

**Comment by MatthiasReccius** [comment]
Using docker works perfectly! Thank you for the quick answer!
