### ISSUE TITLE
Add support for other official NHL streaming providers

### ISSUE THREAD

**Issue by rseanhall** [kompot/nhl-tv-geeky-streams#54]
ESPN received the contract for the NHL broadcasting rights last year for 7 years. It started with the current season (2021-2022). At the beginning of the season, it was revealed that NHL.TV was dropped as the official streaming provider for most of the world and ESPN took up most of that territory. Unfortunately, that makes this project a lot less widely useful.

In my fork, I had to do a lot of refactoring to support multiple providers. I have been able to add support for ESPN+ (USA) and NHL LIVE (Canada). My fork also includes the contents of a pull request here that sat unmerged for a long time. What are your plans for this project? Are you still in NHL.TV territory? If not, are you subscribed to your country's NHL streaming partner? I could look into adding support for your provider if you would use it.

**Comment by kompot** [comment]
Hey @rseanhall, thanks for your interest in the project.

Unfortunately, I don't have time to watch NHL as of now, let alone support this project. I'll be glad to give you permissions to this repository to keep it up to date if you are interested.

**Comment by rseanhall** [comment]
Yes, I'm interested in keeping this up to date because I am actively using it.

**Comment by kompot** [comment]
Sent an invitation.

**Comment by rseanhall** [comment]
Thanks! I pushed my code to master.

There's something that I updated on my fork that I don't have access to here - the About section at the home of the repo. I updated it to "Best way to download NHL games. NHL.TV, NHL LIVE, or WatchESPN account is required.".

**Comment by kompot** [comment]
Thanks, updated the description.
