### ISSUE TITLE
All games unavailable

### ISSUE THREAD

**Issue by RedmaxPens87** [kompot/nhl-tv-geeky-streams#60]
I have NHL TV subscription but all feed is unavailable.
[URL=https://imageban.ru][IMG]https://i1.imageban.ru/out/2022/10/17/43b9975a8b39600e41e78cddce808871.png[/IMG][/URL]

**Comment by rseanhall** [comment]
Unfortunately, they have changed their API and it will require non-trivial code to get it working again. This is already being tracked at https://github.com/kompot/nhl-tv-geeky-streams/issues/59.
