### ISSUE TITLE
--force-progress option has been deprecated

### ISSUE THREAD

**Issue by antiden** [kompot/nhl-tv-geeky-streams#67]
Hi,

`streamlink: [warnings][streamlinkdeprecation] The --force-progress option has been deprecated in favor of --progress=force` in file `download.ts`

need: -`-progress=force`

**Comment by rseanhall** [comment]
Fixed in https://github.com/kompot/nhl-tv-geeky-streams/commit/3f93e122e09c1393ca120807d4fc4452efcec845
