### ISSUE TITLE
Bad downloaded file after last commit

### ISSUE THREAD

**Issue by antiden** [kompot/nhl-tv-geeky-streams#70]
Hi,

After commits in Apr 23, 2023, with passive mode, file load bad, first a folder is created in it a file. Example:

1. created folder video/2023-04-23_EDM_at_LAK_(HOME_RSN_HOME_
2. in this folder have file _HOME)_720p_archive.mp4

**Comment by rseanhall** [comment]
This line needs to be updated to replace / with _: https://github.com/kompot/nhl-tv-geeky-streams/blob/a3b2177766446aefac3a895a0148784249647734/src/index.ts#L262

**Comment by antiden** [comment]
@rseanhall yes, working

**Comment by rseanhall** [comment]
Fixed in https://github.com/kompot/nhl-tv-geeky-streams/commit/94b1a702d5e351935e02be15012c57c1a804ee0f
