### ISSUE TITLE
NHL API change?

### ISSUE THREAD

**Issue by technaustin** [kompot/nhl-tv-geeky-streams#73]
As of today, I have been getting an error with the schedule API. Maybe they updated their API? Outage?

![image](https://github.com/kompot/nhl-tv-geeky-streams/assets/46908628/b7001885-6c5e-4e96-ac11-c43af17f682c)

Uploaded the whole powershell log below if you need more. 

[test2.txt](https://github.com/kompot/nhl-tv-geeky-streams/files/13292712/test2.txt)

**Comment by rseanhall** [comment]
The workaround right now is to enable the config option that was added last year:

```
# whether to use legacy NHL.TV API to get the game status
disableLegacyNhltvGameStatus: true
```

From https://old.reddit.com/r/hockey/comments/16pgdhe/nhl_api_down/, it seems that there might be a new version of the API. Help is always appreciated.

**Comment by technaustin** [comment]
> The workaround right now is to enable the config option that was added last year:
> 
> ```
> # whether to use legacy NHL.TV API to get the game status
> disableLegacyNhltvGameStatus: true
> ```
> 
> From https://old.reddit.com/r/hockey/comments/16pgdhe/nhl_api_down/, it seems that there might be a new version of the API. Help is always appreciated.

Honestly, this workaround is totally fine for me as I am using ESPN. Appreciate your help, it's working great!

**Comment by rseanhall** [comment]
I'm glad the workaround worked for you. Without the legacy NHL.TV API, the app no longer shows you the status of the game. For instance, "2nd Period 14:54" or "Ending soon". I'm going to leave this open since this functionality needs to be fixed, or at least removed so that the app doesn't crash with the default configuration.

**Comment by rseanhall** [comment]
Fixed by https://github.com/kompot/nhl-tv-geeky-streams/commit/a961d76a2e39e938e586260647b9eb42736bd784
