### ISSUE TITLE
No ESPN+ Feeds

### ISSUE THREAD

**Issue by ljcervantes** [kompot/nhl-tv-geeky-streams#78]
I am seeing this:

(base) MacBook-Pro:nhl-tv-geeky-streams-master 2 lesliecervantes$ yarn start --startDate 2023-10-25
yarn run v1.22.19
$ ./node_modules/.bin/ts-node src/index.ts --startDate 2023-10-25
? Choose game to download   Boston Bruins           @ Chicago Blackhawks     
? Choose feed to watch ⤺  (choose different game)
? Choose game to download   Anaheim Ducks           @ Columbus Blue Jackets   
ended, live stream
? Choose feed to watch 
    NHL.TV      HOME      
    NHL.TV      AWAY      
  - WatchESPN   NATIONAL   Feeds delayed 24 hours from game start due to airing 
on NHLPP|ESPN+ (not available)
❯ ⤺  (choose different game)

**Comment by rseanhall** [comment]
I don't see any games for that date on the ESPN+ website either: https://www.espn.com/watch/schedule/_/type/replay/startDate/20231023. You might have to reach out to their support to see why they are delisting games.

**Comment by ljcervantes** [comment]
Yeah- It seems like a lot of the 2023 games are being removed?

**Comment by ljcervantes** [comment]
Sean-

I wanted to ask you a few questions and see if you can help me out for
something else.  I actually called up ESPN+ for this matter but wanted to
chat about something else.

***@***.***

Thanks,
Leslie

**Comment by rseanhall** [comment]
I'm not sure what you wanted to do here. If you want to ask questions you can ask them here. If you wanted to email me directly, my email is in the commit history.
