### ISSUE TITLE
Update but another error

### ISSUE THREAD

**Issue by Redmax87** [kompot/nhl-tv-geeky-streams#82]
[+] Building 0.0s (0/0)                                                                                  docker:default
[+] Building 0.0s (0/0)                                                                                  docker:default
yarn run v1.22.19
$ ./node_modules/.bin/ts-node src/index.ts
/app/node_modules/ts-node/src/index.ts:859
    return new TSError(diagnosticText, diagnosticCodes, diagnostics);
           ^
TSError: ⨯ Unable to compile TypeScript:
src/calcRecordingOffset.ts:47:37 - error TS2315: Type 'Duration' is not generic.

47   let offsetBackToStartRecordingAt: luxon.Duration<true> | luxon.Duration<false> = luxon.Duration.fromMillis(0);
                                       ~~~~~~~~~~~~~~~~~~~~
src/calcRecordingOffset.ts:47:60 - error TS2315: Type 'Duration' is not generic.

47   let offsetBackToStartRecordingAt: luxon.Duration<true> | luxon.Duration<false> = luxon.Duration.fromMillis(0);
                                                              ~~~~~~~~~~~~~~~~~~~~~
src/calcRecordingOffset.ts:109:23 - error TS2315: Type 'Duration' is not generic.

109   let durationOffset: luxon.Duration<true> | luxon.Duration<false> = luxon.Duration.fromMillis(0);
                          ~~~~~~~~~~~~~~~~~~~~
src/calcRecordingOffset.ts:109:46 - error TS2315: Type 'Duration' is not generic.

109   let durationOffset: luxon.Duration<true> | luxon.Duration<false> = luxon.Duration.fromMillis(0);
                                                 ~~~~~~~~~~~~~~~~~~~~~

    at createTSError (/app/node_modules/ts-node/src/index.ts:859:12)
    at reportTSError (/app/node_modules/ts-node/src/index.ts:863:19)
    at getOutput (/app/node_modules/ts-node/src/index.ts:1077:36)
    at Object.compile (/app/node_modules/ts-node/src/index.ts:1433:41)
    at Module.m._compile (/app/node_modules/ts-node/src/index.ts:1617:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Object.require.extensions.<computed> [as .ts] (/app/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Function.Module._load (node:internal/modules/cjs/loader:938:12)
    at Module.require (node:internal/modules/cjs/loader:1115:19) {
  diagnosticCodes: [ 2315, 2315, 2315, 2315 ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
PS F:\nhl-tv-geeky-streams-master\nhl-tv-geeky-streams-master>

**Comment by Redmax87** [comment]
I solved with docker compose build --no-cache
Can delete this issue, sorry.

**Comment by rseanhall** [comment]
I updated the README to recommend running that command after downloading a new version. I also modified the code so it would work with the old packages as well: https://github.com/kompot/nhl-tv-geeky-streams/commit/f4e54131e10d4ec0b8df8eaf0ad421a7e5084adc.

**Comment by Redmax87** [comment]
Great work, thank you.

    On Thursday, October 3, 2024 at 06:39:53 PM GMT+3, Sean Hall ***@***.***> wrote:  
 
 


I updated the README to recommend running that command after downloading a new version. I also modified the code so it would work with the old packages as well: f4e5413.
